FROM jenkins/jenkins:lts

USER root

# Install tools required for ML pipeline
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    jq \
    bc \
    docker.io \
    git \
    && rm -rf /var/lib/apt/lists/*

# Allow Jenkins to use docker
RUN usermod -aG docker jenkins

USER jenkins
